#include "PCH.hpp"

#include "CoreMinimal.hpp"

DEFINE_LOG_CATEGORY(LogGUI);
DEFINE_LOG_CATEGORY(LogCore);
DEFINE_LOG_CATEGORY(LogEngine);
DEFINE_LOG_CATEGORY(LogEntity);
DEFINE_LOG_CATEGORY(LogEntityComponent);
DEFINE_LOG_CATEGORY(LogThreadPool);
DEFINE_LOG_CATEGORY(LogApplication);
DEFINE_LOG_CATEGORY(LogAssetManager);
DEFINE_LOG_CATEGORY(LogRenderer);
DEFINE_LOG_CATEGORY(LogRHI);
DEFINE_LOG_CATEGORY(LogPhysics);
DEFINE_LOG_CATEGORY(LogWorld);
DEFINE_LOG_CATEGORY(LogLevel);